---
mlagBondProfile_switch:
  bridge_vids: [20, 200, 201, 3900, 3902, 3903, 3904, 3906]
  extras:
    - "bond-lacp-bypass-allow yes"
    - "mstpctl-bpduguard no"
    - "mstpctl-portadminedge no"
    - "mtu 9216"

mlagBondProfile_uplink:
  bridge_vids: [20, 116, 3900, 3901, 3902, 3903, 3904, 3906]
  extras:
    - bridge-allow-untagged no
    - "bond-lacp-bypass-allow yes"
    - "mstpctl-portbpdufilter yes"
    - "mtu 9216"

mlagBondProfile_orci:
  bridge_vids: [116, 3900, 3901, 3902]
  extras:
    - "bridge-allow-untagged no"
    - "bond-lacp-bypass-allow yes"
    - "mstpctl-bpduguard no"
    - "mstpctl-portadminedge no"
    - "mtu 9216"

mlagBondProfile_oldcore:
  bridge_vids: [20, 116, 200, 201, 3900, 3901, 3902, 3903, 3904, 3906]
  extras:
    - "bridge-allow-untagged no"
    - "bond-lacp-bypass-allow yes"
    - "mstpctl-bpduguard no"
    - "mstpctl-portadminedge no"
    - "mtu 9216"

mlagBondProfile_server:
  bridge_vids: [20, 200, 201, 3900, 3903, 3904, 3906]
  extras:
    - "bond-lacp-bypass-allow yes"
    - "mstpctl-bpduguard yes"
    - "mstpctl-portadminedge yes"
    - "mtu 9216"

mlagBondProfile_dtn:
  bridge_vids: [200]
  extras:
    - "bridge-pvid 200" 
    - "bond-lacp-bypass-allow yes"
    - "mstpctl-bpduguard yes"
    - "mstpctl-portadminedge yes"
    - "mtu 9216"

mlagBondProfile_orci_oob:
  bridge_vids: [3900, 3902]
  extras:
    - "bond-lacp-bypass-allow yes"
    - "mstpctl-bpduguard no"
    - "mstpctl-portadminedge no"
    - "mtu 9216"
    - "bridge-pvid 3902"

mlagBondProfile_server_campus:
  bridge_vids: [3903]
  extras:
    - "bond-lacp-bypass-allow yes"
    - "mstpctl-bpduguard yes"
    - "mstpctl-portadminedge yes"
    - "mtu 9216"
    - "bridge-pvid 3903"
