---
backup:
  path: "../inventories/{{ fabric_name }}/config/{{ inventory_hostname }}"
  files:
    - "/etc/network/interfaces"
    - "/etc/frr/frr.conf"
    - "/etc/frr/daemons"
dns:
  domain: hyakm.washington.edu
  search_domain:
    - hyakm.washington.edu
  servers:
    ipv4:
      - "10.158.213.78"
      - "128.95.112.122"
      - "128.95.120.104"
    vrf: mgmt
snmp:
  addresses:
    - "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}@mgmt"
  rocommunity: public
syslog:
  servers:
    - 10.158.213.78
ntp:
  timezone: America/Los_Angeles
  server_ips:
    - 10.158.213.78
ssh:
  motd: |
    #########################################################
    Successfully logged in to: {{ inventory_hostname }}
    #########################################################
  banner: |
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Authorized Users Only!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
