---
- hosts: spine leaf
  roles:
    - { role: hostname, tags: ['hostname'] }
    - { role: motd, tags: ['motd'] }
    - { role: dns, tags: ['dns'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: ptm, tags: ['ptm'] }
    - { role: snmp, tags: ['snmp'] }
    - { role: syslog, tags: ['syslog'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: license, tags: ['license']}
    - { role: interfaces, tags: ['interfaces'] }
    - { role: frr, tags: ['frr'] }
    - { role: ebtables, tags: ['ebtables'] }
    - { role: backup, tags: ['backup'] }

- hosts: ethswitches
  become: yes
  tasks:
    - name: Change cumulus password
      user:
        name: cumulus
        update_password: always
        password: "{{ cumulus_user_password|password_hash('sha512') }}"
      changed_when: False
